const MAIN_DECK_LIMIT = 60
const EXTRA_AND_SIDE_DECK_LIMIT = 15

const FORBIDDEN_CARD_LIMIT = 0
const LIMITED_CARD_LIMIT = 1
const SEMI_LIMITED_CARD_LIMIT = 2
const UNRESTRICTED_CARD_LIMIT = 3

const GENESYS_STANDARD_POINT_LIMIT = 100

export { MAIN_DECK_LIMIT, EXTRA_AND_SIDE_DECK_LIMIT, FORBIDDEN_CARD_LIMIT, LIMITED_CARD_LIMIT, SEMI_LIMITED_CARD_LIMIT, UNRESTRICTED_CARD_LIMIT, GENESYS_STANDARD_POINT_LIMIT }